@startuml
'https://plantuml.com/class-diagram

class OrderClient

package "Application Layer" {
    class OrderService
    interface OrderRepository
}

package "Infra Layer" {
    class JpaOrderRepository
}

OrderClient .down.> OrderService: use
OrderService .right.> OrderRepository: use
JpaOrderRepository .up.|> OrderRepository


@enduml