@startuml
'https://plantuml.com/class-diagram

class OrderClient

package "Application Layer" {
    class OrderService
}

package "Infra Layer" {
    class OrderRepository
}

OrderClient .down.> OrderService: use
OrderService .down.> OrderRepository


@enduml